Update README.md
FriendsOfREDAXO/installer-action pull request #25
Opened 2022-05-30 10:00 UTC by danspringer

Readme bzgl. Secrets etwas etwas genauer beschrieben.

2022-05-30 10:03 UTC, alxndr-w commented on README.md
> +The values of your keys are, of course, your MyRedaxo-API-Key and your MyRedaxo-Username.
Das steht schon oben in der Tabelle

2022-05-30 10:05 UTC, alxndr-w commented on README.md
> +You need to add two secrets.
Das steht schon im Satz weiter oben

2022-05-30 10:05 UTC, alxndr-w requested changes
Die Screenshots sind eine Verbesserung, aber ehrlich gesagt verstehe ich nicht, was es besser macht, wenn man 2x das gleiche hinschreibt.

2022-05-30 10:09 UTC, danspringer commented on README.md
> +
Die Tabelle hat dann aber wohl nie sehr gut funktioniert. Die sieht im Moment nämlich so aus:

<img width="814" alt="Bildschirmfoto 2022-05-30 um 12 07 20" src="https://user-images.githubusercontent.com/16903055/170970049-1931b780-0df1-4ea2-b2e1-6a6a3e595c99.png">

Und das hat mich komplett raus gebracht, wie denn nun diese Kombination Key <-> Value auszusehen hat.

2022-05-30 10:11 UTC, alxndr-w commented on README.md
> +
Oh, dann sollte die vielleicht ordentlich formatiert werden.

2022-05-30 10:18 UTC, danspringer commented
> Die Screenshots sind eine Verbesserung, aber ehrlich gesagt verstehe ich nicht, was es besser macht, wenn man 2x das gleiche hinschreibt.

Im Speziellen hatte ich das Problem dass ich die Worte "MYREDAXO_USERNAME" und "MYREDAXO_API_KEY" als Variablen verstanden habe... deshalb wollte ich es explizit nochmal beschreiben, dass die Key so heissen müssen.

2022-05-30 10:23 UTC, alxndr-w commented
Okay, verstehe. Für mich war Common Sense, das Werte in Ticks, die `so formatiert` sind, als exakte Werte zu verstehen sind, aber langsam verstehe ich das Missverständnis.

Das wäre bei den Screenshots jedoch immer noch gegeben, auch da könnte man meinen, es handle sich nur um Beispiele.

Ich mach nochmal einen Gegenvorschlag später.

2022-06-02 13:43 UTC, alxndr-w commented
Dauert noch ein bisschen, ich habe zu viel um die Ohren. Aber so würde ich es ungern reinnehmen.

2022-07-29 10:59 UTC, skerbis commented on README.md
> +
@danspringer die Tabelle ist bereits hier gefixt. https://github.com/FriendsOfREDAXO/installer-action/pull/54

2022-08-03 07:42 UTC, alxndr-w commented on README.md
> +You need to add two secrets.
```suggestion```

2022-08-03 07:44 UTC, alxndr-w requested changes

2022-08-03 07:44 UTC, alxndr-w commented on README.md
> +You need to add two secrets.
```suggestion
```

2022-08-03 07:44 UTC, alxndr-w commented on README.md
> +One has to be named: `MYREDAXO_USERNAME` and the other one has to be named: `MYREDAXO_API_KEY`
```suggestion

```

2022-08-03 07:44 UTC, alxndr-w commented on README.md
> +| key      | value |
```suggestion
| secret name | value |
```

2022-08-03 07:44 UTC, alxndr-w commented on README.md
> +E.g. `MYREDAXO_API_KEY`:
```suggestion
example value for `MYREDAXO_API_KEY` named secret:
```

2023-03-25 09:32 UTC, alxndr-w approved these changes

2023-03-25 09:34 UTC, alxndr-w commented
Von meiner Seite aus passt das so. @bloep / @skerbis ?

2023-03-25 09:40 UTC, merged

2023-03-25 09:40 UTC, bloep commented
danke 👍